services:
  backend:
    build:
      context: ./backend
    container_name: ews-reference-backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:8080
        VITE_SWAGGER_URL: http://localhost:8080/swagger-ui.html
    container_name: ews-reference-frontend
    depends_on:
      - backend
    environment:
      PORT: 5173
    ports:
      - "5173:5173"
